// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
    // ignore: missing_enum_constant_in_switch
/*    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );*/
  }

  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  static const android = FirebaseOptions(
      apiKey: "AIzaSyCaCb8mmZ6nOOak69A5HlJt3u6ddqKkHHs",
      authDomain: "kagemuwaumzug.firebaseapp.com",
      databaseURL: "https://kagemuwaumzug.firebaseio.com",
      projectId: "kagemuwaumzug",
      storageBucket: "kagemuwaumzug.appspot.com",
      messagingSenderId: "978008543828",
      appId: "1:978008543828:android:26e69d9b71552fba4813c1",
      measurementId: "G-T91YPDMHEQ"
  );
}